# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
    filter-kubernetes.conf: |
     [FILTER]
       Name                kubernetes
       Match               kube.*
       Kube_URL            https://kubernetes.default.svc:443
       Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
       Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
       Kube_Tag_Prefix     kube.var.log.containers.
       Merge_Log           On
       Merge_Log_Key       log_processed
       K8S-Logging.Parser  On
       K8S-Logging.Exclude On
       Regex_Parser        k8s-custom-tag
     [FILTER]
       Name    lua
       Match   kube.*
       script  set_index_prefix.lua
       call    set_index_prefix
    fluent-bit.conf: |
     [SERVICE]
       Flush         1
       Log_Level     info
       Daemon        off
       Parsers_File  parsers.conf
       HTTP_Server   On
       HTTP_Listen   0.0.0.0
       HTTP_Port     2020
     @INCLUDE input-kubernetes.conf
     @INCLUDE filter-kubernetes.conf
     @INCLUDE output-elasticsearch.conf
    input-kubernetes.conf: |
     [INPUT]
       Name              tail
       Tag               kube.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
       Tag_Regex         (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
       Path              /var/log/containers/*.log
       Path_Key          log_path
       Exclude_Path      *kube-system*,*fluent-bit*,*prometheus*
       Parser            docker
       DB                /var/log/fluentbit_kube_helm.db
       Mem_Buf_Limit     5MB
       Skip_Long_Lines   On
       Refresh_Interval  10
       Docker_Mode       On
    output-elasticsearch.conf: |
     [OUTPUT]
       Name            es
       Match_Regex     ^kube\.(cms|co2|crm|mv|monitoring|prof)\.
       Host            10.33.41.66
       Path            /elasticsearch
       Port            80
       Replace_Dots    On
       Retry_Limit     5
       Logstash_Format On
       Logstash_Prefix ${ENVIRONMENT}-unknown
       Logstash_Prefix_Key flb-index-prefix
       Include_Tag_Key On
     [OUTPUT]
       Name            es
       Match_Regex     ^kube\.(anc|book|de|ful|mmb|pay|sfb|wifi)\.
       Host            eslb
       Port            9200
       Replace_Dots    On
       Retry_Limit     5
       Logstash_Format On
       Logstash_Prefix ${ENVIRONMENT}-unknown
       Logstash_Prefix_Key flb-index-prefix
       Include_Tag_Key On
     [OUTPUT]
       Name            es
       Match_Regex     ^kube.*\.nginx-ingress
       Host            eslb
       Port            9200
       Replace_Dots    On
       Retry_Limit     5
       Logstash_Format On
       Logstash_Prefix ${ENVIRONMENT}-ingress
       Include_Tag_Key On
    parsers.conf: |
     [PARSER]
       Name   apache
       Format regex
       Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
       Time_Key time
       Time_Format %d/%b/%Y:%H:%M:%S %z
     [PARSER]
       Name   apache2
       Format regex
       Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
       Time_Key time
       Time_Format %d/%b/%Y:%H:%M:%S %z
     [PARSER]
       Name   apache_error
       Format regex
       Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
     [PARSER]
       Name   nginx
       Format regex
       Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
       Time_Key time
       Time_Format %d/%b/%Y:%H:%M:%S %z
     [PARSER]
       Name        k8s-nginx-ingress
       Format      regex
       Regex       ^(?<real_ip>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] \[([^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)
       Time_Key    time
       Time_Format %d/%b/%Y:%H:%M:%S %z
     [PARSER]
       Name        k8s-nginx-ingress-json
       Format      json
       Time_Key    time
       Time_Format %Y-%m-%dT%H:%M:%S.%L
       Time_Keep   On
     [PARSER]
       Name   json
       Format json
       Time_Key time
       Time_Format %d/%b/%Y:%H:%M:%S %z
     [PARSER]
       Name        docker
       Format      json
       Time_Key    time
       Time_Format %Y-%m-%dT%H:%M:%S.%L
       Time_Keep   On
     [PARSER]
       # http://rubular.com/r/tjUt3Awgg4
       Name cri
       Format regex
       Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
       Time_Key    time
       Time_Format %Y-%m-%dT%H:%M:%S.%L%z
     [PARSER]
       Name        syslog
       Format      regex
       Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
       Time_Key    time
       Time_Format %b %d %H:%M:%S
     [PARSER]
       Name    k8s-custom-tag
       Format  regex
       Regex   ^(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})-$
    set_index_prefix.lua: |
      local function is_not_empty(s)
       return not (s == nil or s == '')
      end
      
      local function starts_with(str, start)
       return str:sub(1, #start) == start
      end
      
      function set_index_prefix(tag, timestamp, record)
       local environment = os.getenv("ENVIRONMENT")
       local namespace, container = string.match(tag, "^kube%.([^%.]+)%.([^%.]+)%.")
       if (is_not_empty(environment) and is_not_empty(namespace) and is_not_empty(container)) then
        new_record = record
        new_record["flb-index-prefix"] = generate_index_prefix(environment, namespace, container)
        return 2, timestamp, new_record
       else
        -- do not modify record
        return 0, timestamp, record
       end
      end
kind: ConfiMap
metadata:
    creationTimestamp: "2020-11-30T09:51:29Z"
    labels:
       app.kubernetes.io/instance: fluent-bit
       app.kubernetes.io/managed-by: Tiller
       app.kubernetes.io/name: fluent-bit
       helm.sh/chart: fluent-bit-1.4.6
       k8s-app: fluent-bit
    name: fluent-bit-config
    namespace: logging
    resourceVersion: "68612805"
    selfLink: /api/v1/namespaces/logging/configmaps/fluent-bit-config
    uid: 48d98944-c4d0-4665-b7fd-ace6bd7fc071
